### ISSUE TITLE
Not clear which version of a multi-version product you're looking at

### ISSUE THREAD

**Issue by JBorrow** [simonsobs/soposerve#25]
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/c1cada33-be46-47f9-86ac-75378ce7c117">

**Comment by jernestmyers** [comment]
Would you prefer the displayed-product's version in the product's name or as another badge? Screenshots below.

![image](https://github.com/user-attachments/assets/7baaf204-da68-4641-8e8c-c081e9195945)
![image](https://github.com/user-attachments/assets/72dc65d3-f85b-42fe-b49f-6c75e8cff03f)
